---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-chaincode-external
  labels:
    app: invoice-chaincode-external 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-chaincode-external 
  template:
    metadata:
      labels:
        app: invoice-chaincode-external 
    spec:
      containers:
        - name: invoice-chaincode-external 
          image: scrayorg/hl-fabric-external-invoice-example:1.2 
          imagePullPolicy: Always
          workingDir: /go/src/github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-external 
          env:
          - name: FABRIC_LOGGING_SPEC 
            value: "DEBUG"
          - name: CHAINCODE_ID
            valueFrom:
              configMapKeyRef:
                name: invoice-chaincode-external
                key: chaincode_id
          - name: CHAINCODE_SERVER_ADDRESS
            value: "0.0.0.0:9999"

